CREATE OR REPLACE TABLE DEV_SILVER_DB.S_SUPPLY_CHAIN.S_PAYMENT_METHODS (
  REF_PAYMENT_METHOD STRING PRIMARY KEY,
  DES_PAYMENT_METHOD VARCHAR
);

INSERT INTO DEV_SILVER_DB.S_SUPPLY_CHAIN.S_PAYMENT_METHODS VALUES
  ('CARD', 'Credit or debit card'),
  ('CASH', 'Cash at delivery'),
  ('TRANSFER', 'Bank transfer'),
  ('CRYPTO', 'Cryptocurrency');

  CREATE OR REPLACE TABLE DEV_SILVER_DB.S_SUPPLY_CHAIN.S_ORDERS_CLEAN_COMPLEX AS
SELECT
  ID_ORDER AS ID_ORDER,
  TRY_TO_DATE(DTE_ORDER, 'YYYY-MM-DD') AS DTE_ORDER,
  ID_CUSTOMER AS ID_CUSTOMER,
  ID_PART AS ID_PART,
  CASE 
    WHEN IS_NUMBER(QTY_ORDERED) AND TRY_TO_NUMBER(QTY_ORDERED) > 0 THEN TRY_TO_NUMBER(QTY_ORDERED)
    ELSE NULL 
  END AS QTY_ORDERED,
  TRY_TO_NUMBER(AMT_TOTAL) AS AMT_TOTAL,
  UPPER(REF_PAYMENT_METHOD) AS REF_PAYMENT_METHOD,
  TRY_TO_DATE(DTE_DELIVERY_EST, 'YYYY-MM-DD') AS DTE_DELIVERY_EST,
  DES_ORDER_NOTE AS DES_ORDER_NOTE,
  CURRENT_TIMESTAMP() AS AUD_TST_LOAD,
  CURRENT_USER() AS AUD_USR_LOAD
FROM DEV_BRONZE_DB.B_LEGACY_ERP.B_ORDERS_RAW_COMPLEX
WHERE
  TRY_TO_DATE(DTE_ORDER, 'YYYY-MM-DD') IS NOT NULL
  AND ID_CUSTOMER IS NOT NULL
  AND ID_PART NOT IN ('INVALID')
  AND TRY_TO_NUMBER(AMT_TOTAL) IS NOT NULL;

  
CREATE OR REPLACE VIEW DEV_GOLD_DB.G_SALES.G_ORDERS_BY_PAYMENT_METHOD AS
SELECT
  REF.REF_PAYMENT_METHOD,
  PAY.DES_PAYMENT_METHOD,
  COUNT(*) AS NUM_ORDERS,
  SUM(QTY_ORDERED) AS TOTAL_QTY,
  SUM(AMT_TOTAL) AS TOTAL_REVENUE
FROM DEV_SILVER_DB.S_SUPPLY_CHAIN.S_ORDERS_CLEAN_COMPLEX REF
LEFT JOIN DEV_SILVER_DB.S_SUPPLY_CHAIN.S_PAYMENT_METHODS PAY
ON REF.REF_PAYMENT_METHOD = PAY.REF_PAYMENT_METHOD
GROUP BY REF.REF_PAYMENT_METHOD, PAY.DES_PAYMENT_METHOD;